### ISSUE TITLE
Error in 1.12.2

### ISSUE THREAD

**Issue by ziceptor** [games647/ActionBroadcaster#1]
error https://gist.github.com/ziceptor/6d878931263354261060d36f9e07fb3a
config (utf8) https://gist.github.com/ziceptor/1349cd537b9d245b24bddf75c46474fb

forge-1.12.2-14.23.0.2503-universal.jar
spongeforge-1.12.2-2503-7.0.0-BETA-2720.jar
ActionBroadcaster.jar (v0.5 for Sponge 6.X)

**Comment by TuxCoding** [comment]
Should be fixed with a newer version.
