### ISSUE TITLE
A lot of empty rows /actionbroadcaster list

### ISSUE THREAD

**Issue by ziceptor** [games647/ActionBroadcaster#7]
https://i.imgur.com/EZcnZIp.png
[actionbroadcaster.conf](https://gist.github.com/ziceptor/95e5056e85486c94075c08960b312b08)

forge-1.12.2-14.23.2.2611-universal.jar
spongeforge-1.12.2-2611-7.1.0-BETA-2970.jar
ActionBroadcaster.jar 0.7.1

**Comment by TuxCoding** [comment]
Please post the server log.

**Comment by ziceptor** [comment]
https://gist.github.com/ziceptor/2f325a5962faab0cc0bf7e3fe21b3d3b
